### ISSUE TITLE
Plan to code release？

### ISSUE THREAD

**Issue by Agito555** [V2AI/nuCraft_API#1]
Great job on the work! I'm looking forward to conducting experiments with your dataset. I was wondering if you have any guidelines or API support that could facilitate experiments with your dataset? Additionally, will the code related to the VQ-OCC model be made publicly available?

**Comment by poodarchu** [comment]
1. the dataset is alrady public, you can just replace previous occ datasets with this one seamlessly.
2. vq-occ will be released soon in 1-2 month.
